### ISSUE TITLE
pce.check_connection() fails when connecting to a SaaS PCE instance

### ISSUE THREAD

**Issue by RonGonz-illumio** [illumio/illumio-py#19]
Initiating a connection to the PCE on a customer SaaS instance.

documentation states the following:
> Now that we’ve set up our connection details, we can confirm that our connection is working:
> print(pce.check_connection())
> True
https://illumio-py.readthedocs.io/en/latest/user/quickstart.html

This call fails for no apparent reason, as the underlying exception is not raised with an error message.

For SaaS instances, the endpoint being attempted by the call on [line 339](https://github.com/illumio/illumio-py/blob/main/illumio/pce.py#L339) apparently doesn't exist.  
So maybe add some logic and a SaaS Flag somewhere to avoid making the second call?

## Expected Result
A True response from the check_connection method (i.e. a 200 OK if the connection has succeed (connectivity and authentication)), or alternatively, the exception with an error message to be returned to the caller.

## Actual Result

The first call from [pce.check_connection()](https://github.com/illumio/illumio-py/blob/main/illumio/pce.py#L338
), succeeds with a 200OK.

the second call on [line 339](https://github.com/illumio/illumio-py/blob/main/illumio/pce.py#L339) fails with the following response:

`<Response [406]>`
`b'[{"token":"method_not_allowed_on_saas_cluster","message":"Configuring PCE syslog service is not allowed on SAAS cluster"}]'`

## Steps to reproduce

```python
import illumio
pce = illumio.PolicyComputeEngine('hostname_redacted', org_id='redacted')
    pce.set_credentials('KEY_REDACTED', 'KEY_REDACTED')

    if not (pce.check_connection()):
        print('Connection to PCE failed, check credentials')
        sys.exit()
    else:
        print('Connected to the PCE')

```

**Are you able to help contribute a fix for this issue?** 

I can clone the repo and submit a pull request with suggested code fix if you would like.  However, because I am not familiar with the project, is there additional functionality that can be affected by the fact that the library is being used against a SaaS instance?  I wouldn't know the answer to this so my fix would be fairly limited in scope to just the initial PCE connection check functionality logic.

**Comment by dsommerville-illumio** [comment]
Thanks, this was an oversight on my part. The call to `/settings/events/` was added to verify the `org_id` in the connection check, but I didn't realize the settings endpoints aren't available for SaaS instances.

I'll update the check here to something that will work across both SaaS and on-prem.
