### ISSUE TITLE
expose requests Verify=False to ignore SSL Self Signed Cert connection error for requests in PCE connection string

### ISSUE THREAD

**Issue by RonGonz-illumio** [illumio/illumio-py#25]
## Use case  

internal testing, pce has self-signed Cert

## Example  

```pce = illumio.PolicyComputeEngine(hostname, port='9443', ignoreCert=True)```

to workaround teh issue I added the following to pce.py:

```
from urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(category=InsecureRequestWarning)
requests.packages.urllib3.disable_warnings(requests.packages.urllib3.exceptions.InsecureRequestWarning)
```

in init:

```
self._session = Session()
self._session.verify = False
```

**Comment by dsommerville-illumio** [comment]
Note that you can pass `verify=...` to any PolicyComputeEngine function as all kwargs get passed to the downstream requests call.

I'd also recommend using `verify='/path/to/cert'` per the requests docs for self-signed certs where possible: https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification

I'll add a function to PolicyComputeEngine to set the session verify param in the next update. In the meantime, you can access the `_session` attribute of the pce object:

```
pce = PolicyComputeEngine(hostname, port='9443')
pce._session.verify = False
```
