### ISSUE TITLE
requests SSL cert error exception not raised to check_connection caller

### ISSUE THREAD

**Issue by RonGonz-illumio** [illumio/illumio-py#26]
No way to determine certificate related connection issue from check_connection call

## Expected Result

raise requests cert exception to caller (or at least catch Ex and print requests root cause error message)

## Actual Result

fail to connect - no clue as to why not
connection timeout

## Steps to reproduce

use PCE with self-signed cert

```
pce = illumio.PolicyComputeEngine(hostname, port='9443')
    pce.set_credentials(apiUser, apiKey)

    if not (pce.check_connection()):
        print('Connection to PCE failed, check credentials')
        sys.exit()
    else:
        print('Connected to the PCE')
        return pce
```

**Comment by dsommerville-illumio** [comment]
So as not to break backwards compatibility, I'm going to add a `PolicyComputeEngine::must_connect` function. Identical to `check_connection`, but on failure it will raise the underlying `IllumioApiException` that can be caught and read by the implementer.
