### ISSUE TITLE
calling put results in RequestsJSONDecodeError

### ISSUE THREAD

**Issue by kyongkim-illumio** [illumio/illumio-py#7]
Calling put succeeds but the client raises an exception. Checking the server logs, the operation succeeded and returned a 204 with an empty body

## Expected Result

No exception

## Actual Result

Traceback (most recent call last):
  File ".../.pyenv/versions/3.7.12/lib/python3.7/site-packages/requests/models.py", line 972, in json
    return complexjson.loads(self.text, **kwargs)
  File ".../.pyenv/versions/3.7.12/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File ".../.pyenv/versions/3.7.12/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File ".../.pyenv/versions/3.7.12/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

## Steps to reproduce

```python
import illumio

```

## System Information

Python 3.7.12
MacOS 11.6
illumio            0.8.4

I suspect it's because the response body is empty but now sure.

**Are you able to help contribute a fix for this issue?** yes/no
yes

**Comment by dsommerville-illumio** [comment]
Thanks for the report! Can you provide some reproduction code that shows the issue?

I spun up a fresh 3.7.12 virtual env with just `pip install illumio==0.8.4` but I'm not seeing the `JSONDecode` exception as described.

Normal put calls using `PolicyComputeEngine::put` run ok and correctly return the expected `204`, for example:

```python
from illumio import PolicyComputeEngine

pce = PolicyComputeEngine('my.pce.com')
pce.set_credentials('api_key', 'api_secret')

response = pce.put('/labels/4', json={'value': 'Test'})
print(response.status_code)
```

Trying an update with the wrapper functions for Pairing Profiles as below also runs ok:

```python
from illumio import PolicyComputeEngine

pce = PolicyComputeEngine('my.pce.com')
pce.set_credentials('api_key', 'api_secret')

profile = PairingProfile(name='PP-REPRO')
profile = pce.create_pairing_profile(profile)
pce.update_pairing_profile(profile.href, PairingProfile(
    name='PP-REPRO-UPDATE'
))
```

**Comment by kyongkim-illumio** [comment]
Dumb mistake on my part. The exception was coming from response.json(), not from the CRUD call. response has an empty body which is expected.
